---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: not mysql_installed.stat.exists

- name: Ensure MySQL Python libraries are installed.
  apt:
    name: python-mysqldb
    state: present

- name: Ensure MySQL packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_packages }}"
  register: deb_mysql_install_packages

# http://docs.ansible.com/ansible/latest/apt_key_module.html
- name: Add MySQL repository key
  apt_key:
    # url: http://repo.mysql.com/RPM-GPG-KEY-mysql
    keyserver: pgp.mit.edu
    id: "5072E1F5"
    state: present

- name: Add MySQL Server repository
  apt_repository: repo='deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-5.7' state=present

- name: Add MySQL Python Connector repository
  apt_repository: repo='deb http://repo.mysql.com/apt/ubuntu/ xenial connector-python-2.0' state=present

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Ensure MySQL is stopped after initial install.
  service: "name={{ mysql_daemon }} state=stopped"
  when: mysql_installed.stat.exists == false

- name: Delete innodb log files created by apt package after initial install.
  file: path={{ mysql_datadir }}/{{ item }} state=absent
  with_items:
          - "ib_logfile0"
          - "ib_logfile1"
  when: not mysql_installed.stat.exists
